#pragma once

#include "core/app_contracts.h"

namespace keyboard::ui_text {

enum class TextId {
    WindowTitle,
    Intro,
    ChatboxText,
    FocusInput,
    ShowOverlay,
    HideOverlay,
    ClearInput,
    FillChatbox,
    OpenOptions,
    Status,
    WindowsForeground,
    EditorFocus,
    ThisApp,
    AnotherApp,
    Ready,
    NotSelected,
    WindowsInputLanguage,
    CurrentInputLanguage,
    Detecting,
    NoInputLanguages,
    ImePreviewCandidates,
    Composing,
    ImeCompositionPreview,
    ImeCandidatesAppear,
    Keyboard,
    ImeValidationWarning,
    Shift,
    ShiftOn,
    Backspace,
    KoreanMode,
    Space,
    Enter,
    Hiragana,
    Kanji,
    InputDiagnostics,
    OptionsTitle,
    Close,
    AppLanguage,
    PointerController,
    PointerPositionAdjustment,
    PointerHorizontalOffset,
    PointerVerticalOffset,
    PointerOffsetHint,
    LeftHand,
    RightHand,
    ControllerHandHint,
    SummonButtons,
    HoldDuration,
    HoldRange,
    AtLeastOneButton,
    BindingsMissing,
    BindingsReady,
    BindingInstructions,
    KeyboardLanguageKorean,
    KeyboardLanguageJapanese,
    KeyboardLanguageEnglish,
    CapsLock,
    LeftShift,
    MissingImeTitle,
    MissingImeBody,
    Count,
};

const char *text(UiLanguage language, TextId id);
const char *languageName(UiLanguage language);
std::string controllerButtonLabel(UiLanguage language, ControllerButton button);

} // namespace keyboard::ui_text
